/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JDesktopPane;

/**
 *
 * @author Guilherme
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setContentPane(continente);
        continente.setDragMode(JDesktopPane.OUTLINE_DRAG_MODE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        continente = new javax.swing.JDesktopPane();
        menu = new javax.swing.JMenuBar();
        mCadastrar = new javax.swing.JMenu();
        miCadastrarCliente = new javax.swing.JMenuItem();
        miCadastrarOrdem = new javax.swing.JMenuItem();
        mConsultar = new javax.swing.JMenu();
        miConsultarCliente = new javax.swing.JMenuItem();
        miConsultarOrdem = new javax.swing.JMenuItem();
        mExcluir = new javax.swing.JMenu();
        miExcluirCliente = new javax.swing.JMenuItem();
        miExcluirOrdem = new javax.swing.JMenuItem();
        mEditar = new javax.swing.JMenu();
        miEditarCliente = new javax.swing.JMenuItem();
        miEditarOrdem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        continente.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout continenteLayout = new javax.swing.GroupLayout(continente);
        continente.setLayout(continenteLayout);
        continenteLayout.setHorizontalGroup(
            continenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        continenteLayout.setVerticalGroup(
            continenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        mCadastrar.setText("Cadastrar");

        miCadastrarCliente.setText("Cliente");
        miCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastrarClienteActionPerformed(evt);
            }
        });
        mCadastrar.add(miCadastrarCliente);

        miCadastrarOrdem.setText("Ordem de Serviço");
        miCadastrarOrdem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastrarOrdemActionPerformed(evt);
            }
        });
        mCadastrar.add(miCadastrarOrdem);

        menu.add(mCadastrar);

        mConsultar.setText("Consultar");

        miConsultarCliente.setText("Cliente");
        mConsultar.add(miConsultarCliente);

        miConsultarOrdem.setText("Ordem de Serviço");
        mConsultar.add(miConsultarOrdem);

        menu.add(mConsultar);

        mExcluir.setText("Excluir");

        miExcluirCliente.setText("Cliente");
        mExcluir.add(miExcluirCliente);

        miExcluirOrdem.setText("Ordem de Serviço");
        miExcluirOrdem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExcluirOrdemActionPerformed(evt);
            }
        });
        mExcluir.add(miExcluirOrdem);

        menu.add(mExcluir);

        mEditar.setText("Editar");

        miEditarCliente.setText("Cliente");
        mEditar.add(miEditarCliente);

        miEditarOrdem.setText("Ordem de Serviço");
        mEditar.add(miEditarOrdem);

        menu.add(mEditar);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(continente)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(continente)
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastrarClienteActionPerformed
        FrmCadastraCliente cadastrausuario = new FrmCadastraCliente();
        cadastrausuario.show();
        this.add(cadastrausuario);
    }//GEN-LAST:event_miCadastrarClienteActionPerformed

    private void miCadastrarOrdemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastrarOrdemActionPerformed
        FrmCadastraOrdem cadastraordem = new FrmCadastraOrdem();
        cadastraordem.show();
        this.add(cadastraordem);
    }//GEN-LAST:event_miCadastrarOrdemActionPerformed

    private void miExcluirOrdemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExcluirOrdemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miExcluirOrdemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane continente;
    private javax.swing.JMenu mCadastrar;
    private javax.swing.JMenu mConsultar;
    private javax.swing.JMenu mEditar;
    private javax.swing.JMenu mExcluir;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem miCadastrarCliente;
    private javax.swing.JMenuItem miCadastrarOrdem;
    private javax.swing.JMenuItem miConsultarCliente;
    private javax.swing.JMenuItem miConsultarOrdem;
    private javax.swing.JMenuItem miEditarCliente;
    private javax.swing.JMenuItem miEditarOrdem;
    private javax.swing.JMenuItem miExcluirCliente;
    private javax.swing.JMenuItem miExcluirOrdem;
    // End of variables declaration//GEN-END:variables
}
